name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Only run on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Needed for PyPI trusted publishing & Sigstore
      contents: write    # Needed to create GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Sign the distributions with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: dist/*.tar.gz dist/*.whl

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*